### ISSUE TITLE
Cannot set property 'options' of undefined

### ISSUE THREAD

**Issue by angelhodar** [leodinas-hao/mongoose-query-parser#10]
Hey, I have just installed this package but it just fails with that error simply doing this (it doesnt matter if the query is processed or I just hardcode some values):

```js
app.use("/api/v1/test", (req, res) => {
  const query = MongooseQueryParser().parse(req.query);
  console.log(query);
  res.status(200).send("OK");
});
```

I have installed api-query-params and it works perfectly. What could be the cause? Also, whats exactly the difference between this package and api-query-params? It offers the same as I can see in both README.

**Comment by leodinas-hao** [comment]
Hi @angelhodar , you might want to use `new` key word to initialize the parser like below:

```js
const qry = new MongooseQueryParser().parse(req.query);
```
