### ISSUE TITLE
Blacklist and other options...

### ISSUE THREAD

**Issue by david-emmerich** [leodinas-hao/mongoose-query-parser#11]
Hi,

could it be that the documentation is wrong or deprecated? I just tried to figure out how to add a blacklist and was very confused until I checked the source code where I saw that you can pass it throw the constructor instead of parse() method.

**Comment by leodinas-hao** [comment]
Thanks @david-emmerich. You're right. `blacklist` options should be set in the constructor. I'll update the documentation.
