### ISSUE TITLE
OR from query URI

### ISSUE THREAD

**Issue by rifton007** [leodinas-hao/mongoose-query-parser#13]
Someone can help me, I want to do a OR from request URI.
I tried again and again but without success.

for example (with regex) :
`customer?$or="[{"key1":"/valu/i"},{"key2":"value2"}]"&active=true`

```javascript
//parse return
{ filter: { '$or': { '$in': [Array] }, active: true } }
```
Thanks in advance.

**Comment by aogzpa** [comment]
Hi @rifton007,

you need to enclose it in the filter query string parameter and in JSON format. E.g.:
customer?filter={"$or":[{"key1":"/valu/i"},{"key2":"value2"}]}&active=true
