### ISSUE TITLE
Blacklist not working in JSON filter parameter

### ISSUE THREAD

**Issue by aogzpa** [leodinas-hao/mongoose-query-parser#16]
Good afternoon @leodinas-hao,

I've been using _mongoose-query-parser_ in a project and I've detected that advanced filters passed in the corresponding JSON filter query parameter don't go through the blacklist excluding filter. As a result, you end up having blacklisted keys in the resulting query.

I think it would be a great feature, because several **security issues** arise when this is overlooked.

Thank you and keep up the good work!

**Comment by leodinas-hao** [comment]
Hi @aogzpa, Thank you very much for your PR and it's merged into v1.2.1.

Appreciate your help & support!
