### ISSUE TITLE
$size operator in query parameter

### ISSUE THREAD

**Issue by niklash99** [leodinas-hao/mongoose-query-parser#4]
Hello,
I am currently trying to send a $size array query parameter the request filter parameters.
I´m trying to query by the size of the 'order_items' array.
My request looks like this:
 GET <url>?{ order_items : { $size : 1 }}
The sample query is the MongoDB Manual looks like this:
db.collection.find( { field: { $size: 2 } } );
When is send the request to my server, I don´t get any results. I have tried to change the query, but I can´t figure out how to make it work.

Im happy if there are any suggestions, thank you !

**Comment by leodinas-hao** [comment]
Please try the below link for the relevant docs on paging to control the size of returns:
[https://github.com/leodinas-hao/mongoose-query-parser#skip--limit-operators](https://github.com/leodinas-hao/mongoose-query-parser#skip--limit-operators)
