### ISSUE TITLE
$and operator in query 

### ISSUE THREAD

**Issue by shanmugarajbe** [leodinas-hao/mongoose-query-parser#5]
How to use `$and` operator in the query parameter? I am currently passing query param as` ?attrs.value=Festival&attrs.id=44&attrs.value=Cotton`, but it is parsed as or by default using `$in `operator. How can send in the url in such way that it will be parsed as `$and` ? I need to get the documents matching both `attrs.value` conditions.

Thanks

**Comment by leodinas-hao** [comment]
`$and` is not supported as an operator. The only way for now is to pass in JSON string. An example is as below:
```
parser.parse('filter={"$or":[{"key1":"value1"},{"key2":"value2"}]}&name=Telstra');
// {
//   filter: {
//     $or: [
//       { key1: 'value1' },
//       { key2: 'value2' }
//     ],
//     name: 'Telstra'
//   },
// }
```
It would be really appreciated if you have a PR for supporting `$and`?
